pekoe_web/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('tips/', include('tips.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tips/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'tips'
urlpatterns = [
    path('cafes', views.IndexView.as_view(), name='index'),  # TODO: redirect '' to 'cafes'
    path('cafes/<str:slug>/', views.CafeView.as_view(), name='cafe'),
    # path('cafes/<str:cafe_slug>/<str:waiter_username>', views.WaiterView.as_view(), name='waiter'),
    path('cafes/<str:cafe_slug>/<str:waiter_username>', views.waiterview, name='waiter'),
    path('register', views.registration, name='register'),
    path('login', views.login_user, name='login'),
    path('logout', login_required(views.logout_user), name='logout'),
    path('<str:username>', views.iamview, name='user')
]

tips/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.core.validators import MinLengthValidator


def cafe_upload_path(instance, filename):
    return f"cafe_{instance.slug}/{filename}"

class Cafe(models.Model):
    slug = models.CharField(max_length=20, unique=True, default=uuid.uuid4().hex[:16])
    title = models.CharField(max_length=50)
    location = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to=cafe_upload_path, blank=True)

    def __str__(self):
        return f"Cafe @{self.slug} {self.title}, location: {self.location}"


def user_upload_path(instance, filename):
    return f"user_{instance.username}/{filename}"

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=20, unique=True, default=uuid.uuid4().hex[:16])
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    avatar = models.ImageField(upload_to=user_upload_path, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)  # a admin user; non super-user
    is_superuser = models.BooleanField(default=False)  # a superuser
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return f"User @{self.username}, {self.first_name} {self.last_name}, email: {self.email}"


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    customer_wallet = models.CharField(max_length=42, validators=[MinLengthValidator(42)])

    def __str__(self):
        return f"Customer {self.user.username}, wallet: {self.customer_wallet}"


# automatically add Customer role to User
@receiver(post_save, sender=User)
def create_customer(sender, instance, created, **kwargs):
    if created:
        customer = Customer(user=instance)
        customer.save()


class Waiter(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    waiter_wallet = models.CharField(max_length=42, blank=True, validators=[MinLengthValidator(42)])
    cafe = models.ForeignKey(Cafe, on_delete=models.CASCADE)

    def __str__(self):
        return f"Waiter {self.user.username} in cafe {self.cafe.title}, wallet: {self.waiter_wallet}"


# automatically fill in customer account for waiter
@receiver(pre_save, sender=Waiter)
def create_waiter_account(sender, instance, **kwargs):
    if instance.waiter_wallet == "" or instance.waiter_wallet is None:
        instance.waiter_wallet = instance.user.customer.customer_wallet


class CafeAdmin(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cafe = models.ForeignKey(Cafe, on_delete=models.CASCADE)

    def __str__(self):
        return f"Cafe admin {self.user.username} in cafe {self.cafe.title}"


class Transaction(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)  # TODO: do not delete transactions
    waiter = models.ForeignKey(Waiter, on_delete=models.CASCADE)  # TODO: store addresses? in case of change
    datetime = models.DateTimeField(auto_now=True)
    amount = models.PositiveBigIntegerField()
    comment = models.CharField(max_length=200)

    def __str__(self):
        return (f"Transaction {self.id} from customer {self.customer} to waiter {self.waiter},"
                f"datetime: {self.datetime}, amount: {self.amount}, comment: {self.comment}")

tips/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class NewUserForm(UserCreationForm):
    username = forms.CharField(max_length=20, required=True)
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    email = forms.EmailField(required=True, widget=forms.EmailInput)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.username = self.cleaned_data["username"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class TipForm(forms.Form):
    rub_amount = forms.IntegerField(label="rub_amount")
    comment = forms.CharField(max_length=200)

tips/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django import forms
from django.forms import modelform_factory
from django.contrib.auth.decorators import login_required

from .models import Cafe, Waiter, User, Customer, Transaction
from .forms import NewUserForm, TipForm
from .web3_client import Web3Client


class IndexView(generic.ListView):
    template_name = "tips/index.html"
    context_object_name = "cafes_list"

    def get_queryset(self):
        return Cafe.objects.order_by("-title")[:10]


class CafeView(generic.DetailView):
    model = Cafe
    template_name = "tips/cafe.html"

    def get_object(self):
        return self.model.objects.get(slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CafeView, self).get_context_data()
        context["waiters_list"] = self.object.waiter_set.all()
        context["cafe_admins_list"] = self.object.cafeadmin_set.all()
        return context


class WaiterView(generic.DetailView):
    model = Waiter
    template_name = "tips/waiter.html"

    def get_object(self):
        return self.model.objects.get(cafe=Cafe.objects.get(slug=self.kwargs['cafe_slug']),
                                      user=User.objects.get(username=self.kwargs['waiter_username']))


def waiterview(request, cafe_slug, waiter_username):
    waiter = Waiter.objects.get(cafe=Cafe.objects.get(slug=cafe_slug), user=User.objects.get(username=waiter_username))
    if request.method == "POST":
        form = TipForm(request.POST)
        if form.is_valid():
            rub_amount = form.cleaned_data.get('rub_amount')
            comment = form.cleaned_data.get('comment')
            web3client = Web3Client()
            # buy rub_amount of PEKOE tokens
            buy_status = web3client.buy(request.user.customer.customer_wallet, rub_amount)
            if not buy_status:
                messages.error(request, f"Could not buy {rub_amount} PEKOE tokens...")
                return redirect("tips:waiter", cafe_slug=cafe_slug, waiter_username=waiter_username)
            # transfer rub_amount PEKOE tokens from customer to waiter
            transfer_status = web3client.transfer(request.user.customer.customer_wallet,
                                                  waiter.waiter_wallet, rub_amount, 'CUSTOMER_PK')  # TODO: use Metamask
            if not transfer_status:
                messages.error(request, f"Could not transfer {rub_amount} PEKOE tokens to @{waiter_username}...")
                return redirect("tips:waiter", cafe_slug=cafe_slug, waiter_username=waiter_username)
            # save transaction to db
            txn = Transaction(customer=request.user.customer, waiter=waiter,
                              amount=rub_amount, comment=comment)
            txn.save(force_insert=True)
            # burn and mint tokens from waiter
            fiat_status = web3client.exchange_fiat(waiter.waiter_wallet,
                                                   rub_amount, 'WAITER_PK')  # TODO: to move to waiter page
            if not fiat_status:
                messages.error(request, f"Could not exchange {rub_amount} for fiat for @{waiter_username}...")
                return redirect("tips:waiter", cafe_slug=cafe_slug, waiter_username=waiter_username)
            messages.success(request, f"You've tipped waiter @{waiter_username}!")
            return redirect("tips:waiter", cafe_slug=cafe_slug, waiter_username=waiter_username)
        messages.error(request, f"Could not tip @{waiter_username}")
    form = TipForm()
    context = {
        "waiter": waiter,
        "tip_form": form
    }
    return render(request=request, template_name='tips/waiter.html', context=context)


@login_required
def iamview(request, username):
    web3client = Web3Client()
    user_form_class = modelform_factory(User, fields=['first_name', 'last_name', 'email'],
                                        widgets={'first_name': forms.TextInput, 'last_name': forms.TextInput,
                                                 'email': forms.EmailInput})
    customer_form_class = modelform_factory(Customer, fields=["customer_wallet"], widgets={"customer_wallet": forms.TextInput})
    waiter_form_class = modelform_factory(Waiter, fields=["waiter_wallet"], widgets={"waiter_wallet": forms.TextInput})
    if request.method == "POST":
        user_form = user_form_class(request.POST, instance=request.user)
        customer_form = customer_form_class(request.POST, instance=request.user.customer)
        waiter_forms = {waiter.cafe.slug: waiter_form_class(request.POST, instance=waiter)
                        for waiter in request.user.waiter_set.all()}
        if user_form.is_valid():
            user_form.save()
            if len(user_form.changed_data) > 0:
                messages.success(request, "Your user profile was updated successfully")
            return redirect('tips:user', username=request.user.username)
        if customer_form.is_valid():
            customer_form.save()
            if len(customer_form.changed_data) > 0:
                messages.success(request, "Customer wallet was changed successfully.")
            return redirect('tips:user', username=request.user.username)
        for cafe in waiter_forms:
            if waiter_forms[cafe].is_valid():
                waiter_forms[cafe].save()
                if len(waiter_forms[cafe].changed_data) > 0:
                    messages.success(request, f"Waiter wallet for cafe {cafe} was changed successfully.")
                return redirect('tips:user', username=request.user.username)
    else:
        user_form = user_form_class(instance=request.user)
        customer_form = customer_form_class(instance=request.user.customer)
        waiter_forms = {waiter.cafe.slug: waiter_form_class(instance=waiter) for waiter in request.user.waiter_set.all()}
    context = {
        "user": request.user,
        "waiters_list": request.user.waiter_set.all(),
        "cafe_admins_list": request.user.cafeadmin_set.all(),
        "user_form": user_form,
        "customer_form": customer_form,
        "customer_transactions": request.user.customer.transaction_set.all(),
        "customer_balance":  web3client.balance_of(request.user.customer.customer_wallet),
        "waiter_forms": waiter_forms,
        "cafes_avatars": {waiter.cafe.slug: waiter.cafe.avatar.url
                          for waiter in request.user.waiter_set.all()},
        "waiter_transactions": {waiter.cafe.slug: waiter.transaction_set.all()
                                for waiter in request.user.waiter_set.all()},
        "waiter_balance": {waiter.cafe.slug: web3client.balance_of(waiter.waiter_wallet)
                           for waiter in request.user.waiter_set.all()}
    }
    return render(request=request, template_name="tips/iam.html", context=context)


def registration(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("tips:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="tips/register.html", context={"register_form": form})


def login_user(request):  # custom auth form? OTP?
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.info(request, f"You are now logged in as {username}.")
            return redirect("tips:index")
        messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="tips/login.html", context={"login_form": form})


def logout_user(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("tips:index")

tips/templates/tips/iam.html
<!-- tips/templates/tips/cafe.html -->

{% extends 'base.html' %}

{% block content %}

{% load widget_tweaks %}

{% if request.user.is_authenticated and request.user.username == user.username %}
<div class="media">
    <div class="media-left">
        <figure class="image is-48x48">
        <img src="{{ user.avatar.url }}">
        </figure>
    </div>
    <div class="media-content">
        <p class="title is-4" style="color: ghostwhite;">
            <span class="icon">
                <i class="fa fa-at"></i>
            </span>
            <span>{{ user.username }}</span>
        </p>
        <form method="post">
            {% csrf_token %}
            <div class="field is-horizontal">
                <div class="field-body">
                    <div class="field">
                        <p class="control is-expanded">
                            {{ user_form.first_name|add_class:"input" }}
                        </p>
                    </div>
                    <div class="field">
                        <p class="control is-expanded">
                            {{ user_form.last_name|add_class:"input" }}
                        </p>
                    </div>
                </div>
            </div>
            <div class="field is-horizontal">
                <div class="field-body">
                    <div class="field">
                        <p class="control is-expanded has-icons-left">
                            {{ user_form.email|add_class:"input" }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-envelope"></i>
                            </span>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control">
                            <button class="button is-primary" type="submit">
                                Update
                            </button>
                        </p>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="media-right">
        <p class="title is-4" style="color: ghostwhite;">
            <span class="icon">
                <i class="fa fa-diamond"></i>
            </span>
            <span>{{ customer_balance }} PEKOE</span></p>
    </div>
</div>

<br>

<div class="tabs is-centered is-large is-boxed">
    <ul>
        <li class="tab is-active" onclick="openTab(event, 'customer')">
            <a>
                <span class="icon is-small"><i class="fa fa-user" aria-hidden="true"></i></span>
                <span style="color: ghostwhite;">Customer</span>
            </a>
        </li>
        <li class="tab" onclick="openTab(event, 'waiter')">
            <a>
                <span class="icon is-small"><i class="fa fa-user-plus" aria-hidden="true"></i></span>
                <span style="color: ghostwhite;">Waiter</span>
            </a>
        </li>
        <li class="tab" onclick="openTab(event, 'cafeadmin')">
            <a>
                <span class="icon is-small"><i class="fa fa-user-tie" aria-hidden="true"></i></span>
                <span style="color: ghostwhite;">Cafe Admin</span>
            </a>
        </li>
    </ul>
</div>

<div id="customer" class="tabcontent">
    <div class="media">
        <div class="media-left">
            <figure class="image is-48x48">
              </figure>
        </div>
        <div class="media-content">
            <form method="post">
                {% csrf_token %}
                <div class="field is-horizontal">
                    <div class="field-body">
                        <div class="field">
                            <p class="control has-icons-left is-expanded">
                                {{ customer_form.customer_wallet|add_class:"input" }}
                                <span class="icon is-small is-left">
                                    <i class="fas fa-wallet"></i>
                                </span>
                            </p>
                        </div>
                        <div class="field">
                            <p class="control">
                                <button class="button is-primary" type="submit">
                                    Update
                                </button>
                            </p>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="media-right">
            <p class="subtitle is-6" style="color: ghostwhite;">
                <span class="icon">
                    <i class="fa fa-diamond"></i>
                </span>
                <span>{{ customer_balance }} PEKOE</span>
            </p>
        </div>
    </div>
    {% if customer_transactions %}
    {% for transaction in customer_transactions %}
    <div class="media">
        <div class="media-left">
            <span class="icon">
                <i class="fa fa-credit-card"></i>
            </span>
        </div>
        <div class="media-content">
            <span>
                <p class="subtitle is-6" style="color: ghostwhite;">
                    <span class="icon is-small">
                        <i class="fa fa-diamond"></i>
                    </span>
                    <span>{{transaction.amount}} PEKOE tokens</span>
                    <span>from: @{{transaction.customer.user.username}}</span>
                    <span class="icon is-small">
                        <i class="fa fa-wallet"></i>
                    </span>
                    <span>{{transaction.customer.customer_wallet}}</span>
                    <span>to: @{{transaction.waiter.user.username}}</span>
                    <span class="icon is-small">
                        <i class="fa fa-wallet"></i>
                    </span>
                    <span>{{transaction.waiter.waiter_wallet}}</span>

                  </p>
            </span>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</div>

<div id="waiter" class="tabcontent" style="display: none">
        {% if waiter_forms %}
        {% for key, form in waiter_forms.items %}
        <div class="media">
            <div class="media-left">
                <a href="{% url 'tips:waiter' cafe_slug=key waiter_username=user.username %}">
                <figure class="image is-48x48">
                    <img src="{{ cafes_avatars|get_item:key }}">
                  </figure>
                </a>
            </div>
            <div class="media-content">
            <a href="{% url 'tips:waiter' cafe_slug=key waiter_username=user.username %}">
                <p class="title is-4" style="color: ghostwhite;">
                    @{{ key }}
                </p>
            </a>
            <br>
            <form method="post">
                {% csrf_token %}
                <div class="field is-horizontal">
                    <div class="field-body">
                        <div class="field">
                            <p class="control has-icons-left is-expanded">
                                {{ form.waiter_wallet|add_class:"input" }}
                                <span class="icon is-small is-left">
                                    <i class="fas fa-wallet"></i>
                                </span>
                            </p>
                        </div>
                        <div class="field">
                            <p class="control">
                                <button class="button is-primary" type="submit">
                                    Update
                                </button>
                            </p>
                        </div>
                    </div>
                </div>
            </form>
            </div>
            <div class="media-right">
                <p class="subtitle is-6" style="color: ghostwhite;">
                    <span class="icon">
                        <i class="fa fa-diamond"></i>
                    </span>
                    <span>{{ waiter_balance|get_item:key }} PEKOE</span>
                </p>
            </div>
        </div>
        {% if waiter_transactions|get_item:key %}
        {% for transaction in waiter_transactions|get_item:key %}
        <div class="media">
            <div class="media-left">
                <span class="icon">
                    <i class="fa fa-credit-card"></i>
                </span>
            </div>
            <div class="media-content">
                <span>
                    <p class="subtitle is-6" style="color: ghostwhite;">
                        <span class="icon is-small">
                            <i class="fa fa-diamond"></i>
                        </span>
                        <span>{{transaction.amount}} PEKOE tokens</span>
                        <span>from: @{{transaction.customer.user.username}}</span>
                        <span class="icon is-small">
                            <i class="fa fa-wallet"></i>
                        </span>
                        <span>{{transaction.customer.customer_wallet}}</span>
                        <span>to: @{{transaction.waiter.user.username}}</span>
                        <span class="icon is-small">
                            <i class="fa fa-wallet"></i>
                        </span>
                        <span>{{transaction.waiter.waiter_wallet}}</span>

                    </p>
                </span>
            </div>
        </div>
        {% endfor %}
        {% endif %}
        {% endfor %}
        {% else %}
        <h2 class="subtitle is-6" style="color: ghostwhite;">
            <span class="icon">
                <i class="fa fa-lock"></i>
            </span>
            <span>You are not a waiter anywhere</span>
        {% endif %}
</div>

<div id="cafeadmin" class="tabcontent" style="display: none">
    {% if cafe_admins_list %}
    {% for cafe_admin in cafe_admins_list %}
    <a href="{% url 'tips:cafe' cafe_admin.cafe.slug %}">
        <div class="media">
            <div class="media-left">
                <figure class="image is-48x48">
                    <img src="{{ cafe_admin.cafe.avatar.url }}">
                </figure>
            </div>
            <div class="media-content">
                <p class="title is-4" style="color: ghostwhite;">
                    {{ cafe_admin.cafe.title }} @{{ cafe_admin.cafe.slug }}
                </p>
            </div>
        </div>
    </a>
    {% endfor %}
    {% else %}
    <h2 class="subtitle is-6" style="color: ghostwhite;">
        <span class="icon">
            <i class="fa fa-lock"></i>
        </span>
        <span>You are not a cafe admin anywhere</span>
    {% endif %}
</div>

{% else %}
    <article class="message is-warning">
        <div class="message-body">
            You are not authorized to view this page.
        </div>
        </article>
{% endif %}

<script type="text/javascript">
function openTab(evt, tabName) {
  var i, x, tablinks;
  x = document.getElementsByClassName("tabcontent");
  for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tab");
  for (i = 0; i < x.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" is-active", "");
  }
  document.getElementById(tabName).style.display = "block";
  evt.currentTarget.className += " is-active";
}
</script>

{% endblock content %}

tips/templates/tips/index.html
<!-- tips/templates/tips/index.html -->

{% extends 'base.html' %}

{% block content %}

<div class="columns">
  <div class="column has-text-centered">
    <h1 class="title" style="color: ghostwhite;">Cafes</h1><br>
  </div>
</div>

{% if cafes_list %}

<div id="app" class="row columns is-multiline">

{% for cafe in cafes_list %}
  <div class="column is-3">
      <div class="card large">
        <a href="{% url 'tips:cafe' cafe.slug %}">
          <div class="card-image">
            <figure class="image is-1by1">
              <img src="{{ cafe.avatar.url }}">
            </figure>
          </div>
          <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <img src="{{ cafe.avatar.url }}">
                  </figure>
                </div>
                <div class="media-content">
                  <p class="title is-4">
                      {{ cafe.title }}
                  </p>
                  <p class="subtitle is-6">
                    @{{ cafe.slug|lower }}
                  </p>
                </div>
              </div>
          </div>
        </a>
    </div>
  </div>

{% endfor %}

</div>

{% else %}
<div class="columns">
  <div class="column has-text-centered">
    <h1 class="title" style="color: ghostwhite;">No cafes found.</h1><br>
  </div>
</div>
{% endif %}

</div>

{% endblock content %}

tips/templates/tips/login.html
<!-- tips/templates/tips/register.html -->

{% extends 'base.html' %}

{% block content %}

{% load bulma_tags %}

<div class="register column is-8 is-offset-2">
  <div class="columns">
    <div class="column has-text-centered">
      <h3 class="title" style="color: ghostwhite;">Login</h1><br>
    </div>
  </div>
    <form method="POST" action="" class="box" style="background-color:ghostwhite">
      {% csrf_token %}
      {{ login_form|bulma }}
      <br />
      <button class="button is-block is-fullwidth is-primary is-medium is-rounded is-success" type="submit">
        Login
      </button>
    </form>
    <br>
    <nav class="level">
      <div class="level-item has-text-centered">
        <div>
          <a href="#">Forgot Password?</a>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <a href="{% url 'tips:register' %}">Create an Account</a>
        </div>
      </div>
    </nav>
  </div>
</div>

{% endblock content %}

tips/templates/tips/register.html
<!-- tips/templates/tips/register.html -->

{% extends 'base.html' %}

{% block content %}

{% load bulma_tags %}

<div class="register column is-8 is-offset-2">
  <div class="columns">
    <div class="column has-text-centered">
      <h3 class="title" style="color: ghostwhite;">Register</h1><br>
    </div>
  </div>
    <form method="POST" action="" class="box" style="background-color:ghostwhite">
      {% csrf_token %}
      {{ register_form|bulma }}
      <br />
      <button class="button is-block is-fullwidth is-primary is-medium is-rounded is-success" type="submit">
        Register
      </button>
    </form>
  </br>
  <nav class="level">
    <div class="level-item has-text-centered">
      <div>
        <a href="{% url 'tips:login' %}">Already have an account?</a>
      </div>
    </div>
  </nav>
  </div>
</div>

{% endblock content %}